public static class GameConstants
{
    public static float HEALTH_PER_ENDURANCE = 5f;
    public static float STAMINA_PER_AGILITY = 5f;
    public static float STAMINA_PER_PERCEPTION = 5f;
    public static float MANA_PER_INTELLIGENCE = 5f;
    
    public static float BASE_HEALTH_RESTORE_PROCENTAGE_ON_NEXT_ROUND_STARTED = 0.1f;
    public static float ADDITONAL_HEALTH_RESTORE_PRECENTAGE_ON_NEXT_ROUND_FROM_ENDURANCE = 0.005f;
    public static float ADDITONAL_HEALTH_RESTORE_PRECENTAGE_ON_NEXT_ROUND_FROM_WILLPOWER = 0.002f;
    
    public static float BASE_MANA_RESTORE_PROCENTAGE_ON_NEXT_ROUND_STARTED = 0.1f;
    public static float ADDITONAL_MANA_RESTORE_PRECENTAGE_ON_NEXT_ROUND_FROM_INTELLEGENCE = 0.005f;
    public static float ADDITONAL_MANA_RESTORE_PRECENTAGE_ON_NEXT_ROUND_FROM_WILLPOWER = 0.002f;
}
